archetypeDir           = "archetypes"
author                 = "admin"
baseUrl                = "http://localhost:1313"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
contentDir             = "content"
languageCode           = "en-us"
layoutDir              = "layouts"
publishDir             = "public"
theme                  = "pixyll"
title                  = "Sigstore Blog"
enableEmoji            = true
DefaultContentLanguage = "en"
#disqusShortname        = ""

[Languages]
[Languages.en]
weight = 1

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["post"]
  search_engine = false
  #google_analytics_id = ""
  twitter_username = "projectsigstore"
  paginate = 5
  goatcounterid = "sigstoreblogstage"
