baseurl = "https://blog.sigstore.dev"
DefaultContentLanguage = "en"
title = "Sigstore Blog"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "News and updates from Sigstore, the modern way to sign, verify and protect software."
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = false
  goatcounterid = "sigstorestage"
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

#[Author]
#  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
#  name = "Sigstore"
#  website = "https://sigstore.dev"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2
